services:
  procura-sp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procura-sp-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
